os: linux
dist: xenial
language: python

python:
  - 3.8

services:
  - xvfb

before_install:
  - pip install coverage==4.5.4  # temporary fix for coveralls
  - pip install coveralls
  - pip install python-coveralls
  
install:
  - pip install -r requirements.txt
  - pip install .

before_script: # configure a headless display to test plot generation
  - export DISPLAY=:99.0
  - sleep 3 # give xvfb some time to start

# command to run tests
script:
  - coverage run --source idm setup.py test

after_success:
  - coveralls
